spring:
  rabbitmq:
    host: dev-rabbit
    port: 5672
    username: guest
    password: guest
  datasource:
    url: jdbc:mariadb://mariadb:3306/customers
    username: payetonkaya
    password: Azertyuiop*
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: update
  security:
    user:
      password: c55Pez5sC76AWcZ

management:
  endpoints:
    web:
      exposure:
        include: [ "prometheus" ]